// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: agent_query.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateAgent(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAgent, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
