// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type GlobalConfig struct {
	ID        uuid.UUID
	Config    json.RawMessage
	Version   int64
	CreatedAt time.Time
}
