// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: global_config_query.sql

package queries

import (
	"context"
	"encoding/json"
)

const createGlobalConfig = `-- name: CreateGlobalConfig :one
INSERT INTO global_config (config, version)
VALUES ($1, $2)
RETURNING id, config, version, created_at
`

type CreateGlobalConfigParams struct {
	Config  json.RawMessage
	Version int64
}

func (q *Queries) CreateGlobalConfig(ctx context.Context, arg CreateGlobalConfigParams) (GlobalConfig, error) {
	row := q.db.QueryRowContext(ctx, createGlobalConfig, arg.Config, arg.Version)
	var i GlobalConfig
	err := row.Scan(
		&i.ID,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVersionGlobalConfig = `-- name: GetLatestVersionGlobalConfig :one
SELECT id, config, version, created_at 
FROM 
    global_config 
ORDER BY 
    version DESC LIMIT 1
`

func (q *Queries) GetLatestVersionGlobalConfig(ctx context.Context) (GlobalConfig, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionGlobalConfig)
	var i GlobalConfig
	err := row.Scan(
		&i.ID,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
