// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	request "controller-service/internal/api/request"
	response "controller-service/internal/api/response"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIControllerService is a mock of IControllerService interface.
type MockIControllerService struct {
	ctrl     *gomock.Controller
	recorder *MockIControllerServiceMockRecorder
}

// MockIControllerServiceMockRecorder is the mock recorder for MockIControllerService.
type MockIControllerServiceMockRecorder struct {
	mock *MockIControllerService
}

// NewMockIControllerService creates a new mock instance.
func NewMockIControllerService(ctrl *gomock.Controller) *MockIControllerService {
	mock := &MockIControllerService{ctrl: ctrl}
	mock.recorder = &MockIControllerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIControllerService) EXPECT() *MockIControllerServiceMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockIControllerService) GetConfig(ctx context.Context) (*response.ConfigResponse, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx)
	ret0, _ := ret[0].(*response.ConfigResponse)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockIControllerServiceMockRecorder) GetConfig(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockIControllerService)(nil).GetConfig), ctx)
}

// RegisterAgent mocks base method.
func (m *MockIControllerService) RegisterAgent(ctx context.Context, name string) (*response.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAgent", ctx, name)
	ret0, _ := ret[0].(*response.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAgent indicates an expected call of RegisterAgent.
func (mr *MockIControllerServiceMockRecorder) RegisterAgent(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAgent", reflect.TypeOf((*MockIControllerService)(nil).RegisterAgent), ctx, name)
}

// UpdateConfig mocks base method.
func (m *MockIControllerService) UpdateConfig(ctx context.Context, payload request.UpdateConfigRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockIControllerServiceMockRecorder) UpdateConfig(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockIControllerService)(nil).UpdateConfig), ctx, payload)
}
