// Code generated by MockGen. DO NOT EDIT.
// Source: database.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	queries "controller-service/internal/repository/sqlc"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockIRepository) CreateAgent(ctx context.Context, name string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", ctx, name)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockIRepositoryMockRecorder) CreateAgent(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockIRepository)(nil).CreateAgent), ctx, name)
}

// CreateGlobalConfig mocks base method.
func (m *MockIRepository) CreateGlobalConfig(ctx context.Context, arg queries.CreateGlobalConfigParams) (queries.GlobalConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGlobalConfig", ctx, arg)
	ret0, _ := ret[0].(queries.GlobalConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGlobalConfig indicates an expected call of CreateGlobalConfig.
func (mr *MockIRepositoryMockRecorder) CreateGlobalConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGlobalConfig", reflect.TypeOf((*MockIRepository)(nil).CreateGlobalConfig), ctx, arg)
}

// GetLatestVersionGlobalConfig mocks base method.
func (m *MockIRepository) GetLatestVersionGlobalConfig(ctx context.Context) (queries.GlobalConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersionGlobalConfig", ctx)
	ret0, _ := ret[0].(queries.GlobalConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersionGlobalConfig indicates an expected call of GetLatestVersionGlobalConfig.
func (mr *MockIRepositoryMockRecorder) GetLatestVersionGlobalConfig(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersionGlobalConfig", reflect.TypeOf((*MockIRepository)(nil).GetLatestVersionGlobalConfig), ctx)
}

// WithTx mocks base method.
func (m *MockIRepository) WithTx(tx *sql.Tx) *queries.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*queries.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockIRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockIRepository)(nil).WithTx), tx)
}
