// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAgentService is a mock of IAgentService interface.
type MockIAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentServiceMockRecorder
}

// MockIAgentServiceMockRecorder is the mock recorder for MockIAgentService.
type MockIAgentServiceMockRecorder struct {
	mock *MockIAgentService
}

// NewMockIAgentService creates a new mock instance.
func NewMockIAgentService(ctrl *gomock.Controller) *MockIAgentService {
	mock := &MockIAgentService{ctrl: ctrl}
	mock.recorder = &MockIAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentService) EXPECT() *MockIAgentServiceMockRecorder {
	return m.recorder
}

// RegisterAgent mocks base method.
func (m *MockIAgentService) RegisterAgent(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAgent", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAgent indicates an expected call of RegisterAgent.
func (mr *MockIAgentServiceMockRecorder) RegisterAgent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAgent", reflect.TypeOf((*MockIAgentService)(nil).RegisterAgent), ctx)
}
